In [ ]:
import numpy as np


In [ ]:
ar1 = np.array([10,20,30,40,50])
print(ar1)
ar2 = np.arange(5)
print(ar2)

In [ ]:
ar = ar1 - ar2
ar

In [ ]:
# Takes range and total values to be in between range
ar = np.linspace(1,10,10)
ar

In [ ]:
# creat array of zeroes for the given shape
np.zeros((2,3))

In [ ]:
# create array of ones for the given shape
np.ones((6,3,2))

In [ ]:
# this functino fill the given value within the given shape
np.full((3,4),4)

In [56]:
# STACKING ARRAYS
# It is done using np.hstack() for horizontal stacking (number of row should be same)
# np.vstack() for vertical stacking (number of columns should be same) 
lst1 = [[1,2],[3,4]]
lst2 = [[6,5],[7,8]]
ar1 = np.array(lst1)
ar2 = np.array(lst2)
np.hstack((ar1,ar2))

array([[1, 2, 6, 5],
       [3, 4, 7, 8]])

In [61]:
# reshape function is used to reshape the given array
np.arange(6).reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [62]:
# Q >> np.reshape(ar, -1) What will be the ouput ? 

In [71]:
# ar = np.array([[1, 2, 3, 4, 5],
#       [6, 7, 8, 9, 10],
#       [11, 12, 13, 14, 15],
#       [16, 17, 18, 19, 20]]
# )

# Reshape the above array in 

# array([[ 1,  3],
#        [ 5,  7],
#        [ 9, 11],
#        [13, 15],
#        [17, 19]])

In [76]:
# QUES
# ar  = np.array([[1, 5],
#  [3, 7],
#  [4, 9]])

# np.reshape(p, (1, -1)) >> what will be the output
