In [1]:
import pandas as pd

In [2]:
df1 = pd.DataFrame({
    'id':[0,1,2],
    'name':['ayan','himanshu','sajid']
})
df1.head()

id      name
0   0      ayan
1   1  himanshu
2   2     sajid

In [16]:
df2 = pd.DataFrame({
    'id':[4,5,6,0],
    'branch':['cse','me','ee','textile']
})
df2.head()

id   branch
0   4      cse
1   5       me
2   6       ee
3   0  textile

In [17]:
pd.merge(left=df1,right=df2,on='id',how = 'inner')

id  name   branch
0   0  ayan  textile

In [18]:
pd.merge(left=df1,right=df2,on='id',how='outer')

id      name   branch
0   0      ayan  textile
1   1  himanshu      NaN
2   2     sajid      NaN
3   4       NaN      cse
4   5       NaN       me
5   6       NaN       ee

In [19]:
pd.merge(how='left',left=df1,right=df2,on='id')

id      name   branch
0   0      ayan  textile
1   1  himanshu      NaN
2   2     sajid      NaN

In [20]:
pd.merge(how='right',left=df1,right=df2,on='id')

id  name   branch
0   4   NaN      cse
1   5   NaN       me
2   6   NaN       ee
3   0  ayan  textile

In [40]:
import numpy as np 
ar = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

In [41]:
ar

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [47]:
ar[1:3,:] = ar[3:0:-1,:]

In [49]:
df1

id      name
0   0      ayan
1   1  himanshu
2   2     sajid

In [53]:
df1.id.dtype

dtype('int64')

In [56]:
df1.id = df1.id.astype('float64')# int64  String

In [57]:
df1.id.dtype

dtype('float64')

In [58]:
ar

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12],
       [ 5,  6,  7,  8]])

In [61]:
ar[ar % 2 == 0]

array([ 2,  4, 10, 12,  6,  8])

In [62]:
temp = ar[1].copy()
ar[1] = ar[2]
ar[2] = temp 


In [66]:
ar1 = np.array([1,2,3])
ar2 = np.array([4,2,5,6])

In [67]:
np.intersect1d(ar1,ar2)

array([2])

In [70]:
np.setdiff1d(ar2,ar1)

array([4, 5, 6])

In [72]:
ar1 == ar2

C:\Users\MSI\AppData\Local\Temp/ipykernel_21460/332039020.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  ar1 == ar2


False