## Machine Learning


In [ ]:
print('hello world')
a = 10
b=20
print(a/b)
print(int(a/b))
print(a//b)
print(a**b)


In [ ]:
print('ds')

In [ ]:

print( (3 < 4) or (5 > 6)  )

#### Strings

In [ ]:
str = "   welcome here  "
str[0]

In [ ]:
# stipe the left side space
str = str.lstrip()
str[0]
str[-1]


In [ ]:
# stripe the right side space
str = str.rstrip()
str[-1]

In [ ]:
# strip from both side
str = str.strip()
print(str[0])
print(str[-1])

In [ ]:
str = 'tosif'
str[1::2]

In [ ]:
str[::-1]


In [ ]:
str[::-1]

In [ ]:
a = 'tosif'
b = 'khan'
c = 'mm'
print('first name is {0} and last name is {1} and {2}'.format(a,b,c))

print('first name is' , a ,'last name is ' , b)


In [ ]:
a,b = 'himanshu','baretha'
print(a,b)

In [ ]:
'eeeeewelcomeeeeeeee'.lstrip('e')

In [ ]:

'welcome'.lstrip('w')

In [ ]:
sent = 'welcome to dewas'
sentList = sent.split()
sentList
'tosif'.join(sentList)

### List

In [ ]:
num = [1,2,3,4,'tosif',2.0]
num

In [ ]:
num[0]

In [ ]:
type(num)

In [ ]:
if isinstance(num,list):
    print("yes its is")

In [ ]:
a = [1,2,3,4,5]
a

In [ ]:
a[1] = 10
a

In [ ]:
a[1:3] = [34,65]
a

In [ ]:
a[2] = 11

In [ ]:
a

In [ ]:
a[1:4]  = [12,65,78]
a

In [ ]:
a.pop()
a

In [ ]:
a.pop()
a

In [ ]:
a.pop(1)

In [ ]:
a = [1,2,3,4,5]
a

In [ ]:
removeItem = a.pop(2)
print(removeItem)
print(a)

In [ ]:
a.append(34)
a

In [ ]:
a.insert(1,11)
a

In [ ]:
short = [12,13,14,15]
a.extend(short)
a

In [ ]:
short =[323,434]
a  = a + short
a

In [ ]:
a = [1,2,3]
a = a*2
a

In [ ]:
a.remove(2)
a

In [ ]:
a.clear()
a

In [ ]:
a = [1,2,3]
a

In [ ]:
del a[1]
a

In [ ]:
del a
a

In [ ]:
a = [1,2,3]
a.extend([4])
a

In [ ]:
a.append([5,6])
a



In [ ]:
a[4]

### TUPLE

In [ ]:
tup = (1,2,3,'TOSIF',4,5)


In [ ]:
tup[1:4]

In [ ]:
del tup


In [ ]:
tup = (1,2,3,4)
myList = list(tup)
myList = tuple(myList)
myList


In [ ]:
for val in myList:
    print(val)

In [ ]:
tup1 = (1,2,3)
tup2 = (4,5,6)
print(tup1 + tup2)


In [ ]:
tup1 * 3

### Sets

In [ ]:
mySet = {1,3,'T',4,5,5}
mySet

In [ ]:
mySet = {1,3,4,5,5}
mySet

In [ ]:
mySet.add(5)
mySet

In [ ]:
mySet.discard(1)
mySet

In [ ]:
mySet.update([1,23])

In [ ]:
mySet

In [ ]:
mySet.pop()

In [ ]:
mySet

In [ ]:
s = {12,43,23,54,333,411}
s.pop()
s

In [ ]:
s1 = {1,2,3,4,5}
s2 ={1,2,6,7,8}
s1 | s2

In [ ]:
s1 & s2

### Dictionaries

In [ ]:
profile = {'first':'tosif','last':'khan'}

profile.get('kered','key not found')

In [ ]:
profile['first']

In [ ]:
for k,v in profile.items():
    print(k)
    print(v)


In [ ]:
for keys in profile:
    print(v)

In [ ]:
for value in profile.values():
    print(value)

In [ ]:
profile.values()

In [ ]:
del profile['last']

In [ ]:
profile

In [ ]:
profile['last'] = 'khan'

In [ ]:

profile.setdefault('nice','empty')

In [ ]:
profile

In [ ]:
profile['first'] = 'ayan'
profile

In [ ]:
profile['ss'] = 'de'

In [ ]:
profile

In [ ]:
profile.fromkeys(['first','last'],)

In [ ]:
num =0
if num > 10:
    print('true')
elif num < 10:
    pass
else:
    print('falser')

In [ ]:
for i in range(1,10):
    if i == 7:
        break
    print(i)
    

In [ ]:
l = [1,2,3,4,5]
i = 0
while i < len(l):  # i < 5 # 0,1,2,3,4
    print(l[i])
    i+=1
    

In [ ]:
for i in l: #[1,2,3,4,5,6,7,8,9]
    print(i)

In [ ]:
sent = ['words','are','awesome']


In [ ]:
for i in sent:
    print(i)

In [ ]:
newSent=[]
for val in sent:
    newSent.append(val)
newSent

In [ ]:
vowels = ['a','e','i','o','u']
newSent = []
for val in sent:
    if val[0] in vowels:
        newSent.append(val)
newSent
    

In [ ]:
sent = ['WorDs','ARe','AweSoME']

newSent = [alp  for word in sent for alp in word if alp.isupper()]

# for val in sent:
#     #words,are ,awesome
#     for alp in val:
#         if alp.isupper():
#             newSent.append(alp)
newSent

In [ ]:
std = { 0 : [12,'ayan'],
        1 : [34,'himanshu'],
        3 : [32,'aliyanz'],
        4 : [56,'sajid']   }

present = [v[1] for k,v in std.items() if v[0] < 50 ]

# for k,v in std.items():
#     if v[0] < 50:
#         present.append(v[1])
present

In [ ]:
vowels

In [ ]:
std

In [ ]:
v_std = [v[1] for k,v in std.items() if v[1][0] in vowels]
# for k,v in std.items():
#     if  v[1][0] in vowels:
#         print(v[1])
v_std

In [ ]:
vowels

In [ ]:
std

In [ ]:
n_dict= { k:v for k,v in std.items() if v[1][0] in vowels}
# for k,v in std.items():
#     if v[1][0] in vowels:
#         n_dict[k] = v
n_dict

### Functions

In [ ]:
def fun():
    print('this is function')
    
    

In [ ]:
fun()

In [ ]:
def add(a,b):
    return a + b

In [ ]:
add(12,3)

In [ ]:
def addItems(*args):
    print(args)

In [ ]:
addItems(1,2,3,4,54,5)

In [ ]:
tup = (1,2,3,4)
sum = 0
for val in tup:
    sum += val
print(sum)
 

In [ ]:
def ayan(n):
    for i in range(n):
        if i % 2 == 0:
            print(i)

In [ ]:
ayan(10)

In [ ]:
even = ayan

In [ ]:
odd = lambda x :  x % 2 != 0
print(odd(13))

In [ ]:
l = [1,2,3,4,5,6]
def square(n):
    return n*n

map(square,l)


# NumPy

It is an fundamental package which is used for scientfic computation in python
It consist of robust data structure which is called multi dimensional array


Numerical Python extensively effecient for efficient mathematical learning It allows user to store large amount of numerical data in the form of array using less memory  and perform extensive operation effeciently

Numpy array stores homogeneous numerical data

In [ ]:
import numpy as np

In [ ]:
# perform calculation over the entire array 
# without using any loop
ar = np.array([1,2,3,4])
type(ar)

In [ ]:
lst = [1,3,4,'tosif']
print(lst)
ar = np.array([1,34,32,2.5])
print(ar)

In [ ]:
# lst = [1,2,3,4,5,6]
# for i in range(len(lst)):
#     lst[i] = lst[i]+5
# lst
ar = ar + 5


In [ ]:
# perform arithmetic operation on numpy array
# speed of execution
ar * 10.5
ar / 10

In [ ]:
# Methos and operation on numpy
l1 = [1,2,67,3]
l2 = [5,6,7]
l1+l2

In [ ]:
ar1 = np.array(l1)
ar2 = np.array(l2)
ar1 + ar2

In [ ]:
ar = np.array([1.0,True])
# True  1 False 0
ar



In [ ]:
# Operation over 1-D array
height = [32,43,34,3,4,6,5,7,8,45,423,54,786,756453,3,676,43,23,342,43543,3,3,45,432,12,56,76,456,43]
ar = np.array(height)

In [ ]:
ar.size

In [ ]:
print(ar.shape)
print(ar.size)
print(len(ar))

In [ ]:
# problem to calculate BMI using array of height and weight
height = [165,456,3423,43,5,4356,546]
weight = [345,654,435,654,34,34,6]
# bmi = w / (h**2)
ar_h = np.array(height)
ar_w = np.array(weight)

ar_bmi = ar_w / ar_h ** 2
ar_bmi

In [ ]:
# fetch first element 
ar[0]
ar[-1]
# fetch last element 

In [ ]:
# perform logical operation on numpy 
ar_h[ar_h > 160]


In [ ]:
np.max(ar_h)
np.min(ar_h)

ar_h.mean()
np.median(ar_h)


In [ ]:
ar_h[::-1]

In [ ]:
# Q3: From a given array, extract all the elements which are greater than 'm' and less than 'n'. Note: 'm' and 'n' are integer values provided as input?
m = 100
n = 3423

ar_h[ (ar_h > m )& (ar_h <= n)]
vl = np.logical_and(ar_h>m , ar_h<n)
ar_h[vl]


In [ ]:
# Q1:
ar = np.array([1,2,3,4,5,6]) 
ar[1::2]

# Q2: Extract all the elements with an odd index?



# Q4:You are provided with 2 lists that contain the data of an ecommerce website. 
# The first list contains the data for the number of items sold for a particular product
#  and the second list contains the price of the product sold. 
number = [8, 9, 9, 1, 6, 9, 5, 7, 3, 9, 7, 3, 4, 8, 3, 5, 8, 4, 8, 7, 5, 7, 3, 6, 1, 2, 7, 4, 7, 7, 8, 4, 3, 4, 2, 2, 2, 7, 3, 5, 6, 1, 1, 3, 2, 1, 1, 7, 7, 1, 4, 4, 5, 6, 1, 2, 7, 4, 5, 8, 1, 4, 8, 6, 2, 4, 3, 7, 3, 6, 2, 3, 3, 3, 2, 4, 6, 8, 9, 3, 9, 3, 1, 8, 6, 6, 3, 3, 9, 4, 6, 4, 9, 6, 7, 1, 2, 8, 7, 8, 1, 4]
price = [195, 225, 150, 150, 90, 60, 75, 255, 270, 225, 135, 195, 30, 15, 210, 105, 15, 30, 180, 60, 165, 60, 45, 225, 180, 90, 30, 210, 150, 15, 270, 60, 210, 180, 60, 225, 150, 150, 120, 195, 75, 240, 60, 45, 30, 180, 240, 285, 135, 165, 180, 240, 60, 105, 165, 240, 120, 45, 120, 165, 285, 225, 90, 105, 225, 45, 45, 45, 75, 180, 90, 240, 30, 30, 60, 135, 180, 15, 255, 180, 270, 135, 105, 135, 210, 180, 135, 195, 225, 75, 225, 15, 240, 60, 15, 180, 255, 90, 15, 150, 230, 150]
ar_num = np.array(number)
ar_price = np.array(price)
#a)How many different products are sold by the company in total?
print(ar_num.size)
#b)How many items were sold in total?
print(ar_num.sum())
#c)What is the average price of the products sold by the e-commerce company?
print(ar_price.mean())
#d)What is the price of the costliest item sold?
print(ar_price.max())
#e)What is the total revenue of the company? [Revenue = Price*Quantity]
print(ar_num * ar_price)
#f)Demand for the 20th product on the list is higher than that for the 50th product. [True/False]
print(ar_num[19] > ar_num[49])
#g)How many products fall under the category of expensive goods?
#An expensive good is one whose price is higher than the average price of the products sold by the company.
avg = ar_price.mean()
ar_price[ar_price > avg]

In [ ]:
# MULTI DIMENSIONAL ARRAY
ar = np.array([23,45,765,87,5643]) # 1D array
print(ar.ndim)
ar = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(ar.ndim)
ar = np.array([
    [
        [1,2,3],
        [3,4,5]
    ],
    [
        [54,34,12],
        [7,8,9]
    ]
])
print(ar.ndim)

In [ ]:
ar = np.array([
    [[1,2,3],
    [9,4,6],],
    
    [[1,2,3],
    [9,4,6],],
    [[1,2,3],
    [9,4,6],]
])
print(ar.ndim)
ar.shape


In [ ]:
ar.itemsize

In [ ]:
ar = np.array([
    [1,2,3],
    [4,5,6]
    ])
ar.ndim

ar * [1,2,3]


In [ ]:
a = np.array([[1,2],[3,4]])
a.ndim

In [ ]:
# axis 0 > row 
# asix 1 > columns

ar  = np.array([[1,2,3,4,5],[6,7,8,9,10]])
# ar[0][1]
ar

In [ ]:
# fetch row col from 2d array
# print(a[0])
# print(a[0][1])
a[1,:]


In [ ]:
# Q) Extract all the border rows and columns from a 2-D array.
# [[11 12 13 14]
#  [21 22 23 24]
#  [31 32 33 34]]
ar = np.array([[11, 12, 13, 14],
               [21, 22, 23, 24],
               [31, 32, 33, 34]])

ar[1,1:3]

In [ ]:
# The indexing and slicing of nD arrays are similar to those of 1D arrays.
#  The only difference between the two is that you need to give the slicing and indexing instructions for each dimension separately. See example below:

In [ ]:
ar[ar[:,0]>11,0]

In [ ]:
ddnumpy.array([1,2,43])